### ISSUE TITLE
null in ie

### ISSUE THREAD

**Issue by georgetmayorga** [still-life-studios/txt.wav#1]
On IE and Edge, every sentence becomes prefixed with the string "null". This appears to be caused by the code that clears the element content with:
  el.innerHTML = null;
Changing that to a blank string fixes the issue for me, i.e.
  el.innerHTML = "";

**Comment by msarchet** [comment]
I'm not sure about it's support but `el.innerHTML.replace(null)` should achieve what you want

**Comment by georgetmayorga** [comment]
closed with 2f5d64072b46dced2efe2a54a8d473e4fe30dabd
